language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'

jobs:
  include:
    - stage: Test coverage
      script:
        - npm run test:cov
        - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: lint style
      script: npm run lint
